### ISSUE TITLE
Field Papers uses Toner for overviews

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#124]
This should be configurable so that an offline source can be used.

**Comment by ranchodeluxe** [comment]
Unclear about what user story perspective is here:

0. (user and admin): As an admin I want to setup `fp-web` to ONLY offer users offline TMS layers during their atlas composition so I'm editing `provider.json` and only offering something like `file:///usr/local/src/{z}/{x}/{y}.png`

0. (admin only): As an admin I want to setup `fp-web` with all `provider.json` layers options but all the `/atlas` index overviews will use an overview override -- so I'm going to set a specific environment variable. No user choice here

To grok the code a little better I went ahead and implemented **2** ( https://github.com/fieldpapers/fp-web/compare/124_toner_overviews?expand=1 ), but **1** seems like the way to go since all other map overviews seems to pull the baselayer option from the `@atlas.provider` chosen during atlas composition.

**Comment by mojodna** [comment]
I was referring to the header ("overview" is a poorly overloaded term), since Toner isn't available offline. **2** is what I meant, awesome.

![image](https://cloud.githubusercontent.com/assets/45/15278265/19e8463a-1acb-11e6-9ded-613620d182e7.png)

It's just about the index view, since as you point out, the detail pages all pull from `@atlas.provider`, which can be assumed to be available offline since they were (probably) created offline.
