### ISSUE TITLE
Implement OMK/ODK form management in OSM Export Tool

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#136]
This can serve as the starting point for other forms / a registry of common forms.

The existing preset management would be a good place to start, as the paradigm is basically the same as we'd want for forms.

**Comment by hallahan** [comment]
Are you referring to the HOT Export Tool?

I was having problems accessing the pyxform dependencies from the admin user. It's cumbersome trying to drive all of these functionalities that are locked to a user from admin. Also, I don't think it's worth the work adding ODK forms to the export tool. Where is there added value?

Since we didn't really use the Export Tool for getting our forms, I vote to cut this out all together. 

I think it makes more sense to just handle forms in OMK. We pre-stock with a set of good forms to start with. We could extend that with creating templates and generating forms automatically from that, but I think that should be in OpenMapKit Server.

**Comment by mojodna** [comment]
Yes, HOT Export Tool.

I'm also not totally convinced that we want to do this either, but wanted to track it for @dalekunce to consider value and priority (or cut).

**Comment by hallahan** [comment]
Let's close this issue. Having XForms in the HOT Export Tool wouldn't be useful, since we have good defaults in OMK Server already.
