### ISSUE TITLE
posm-carto missing svg

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/posm#181]
saw this in the console log on a newly updated posm.

<img width="864" alt="screen shot 2016-06-14 at 12 58 33 pm" src="https://cloud.githubusercontent.com/assets/1913857/16051914/c621ce3c-322f-11e6-9a2b-5e058cd9d9fd.png">

**Comment by almccon** [comment]
Interesting. That's a folder that I borrowed unchanged from https://github.com/AmericanRedCross/hdm-style.tm2/tree/master/img/humanitarian/site, and `common.svg` doesn't exist there either. Investigating...

**Comment by almccon** [comment]
I guess when I was translating the vector tile source from https://github.com/AmericanRedCross/hdm-style.tm2 back into a plain old TileMill project, I included some things as HDM features that I didn't need to. `leisure=common` is already getting rendered as a green park-like area, so it doesn't need an extra icon (which doesn't exist anyway). 

Fixed in https://github.com/AmericanRedCross/posm-carto/commit/d128a511998911356cb7490e2346b9100dad7480
