### ISSUE TITLE
Automate device data provisioning (aka posm-admin)

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#31]
See the [sample](https://github.com/AmericanRedCross/posm/blob/master/STEPS.md#create-a-data-manifest-describing-everything).

Needs to add a timestamp and/or relevant serial numbers, etc. to help sync + update (or use a UUID pointing to an external source (e.g. HOT Export Tool) where they can be retrieved from).

/cc @jflemer-ndp

**Comment by jflemer-ndp** [comment]
Also:
> should this include some sync metadata? what urls to connect to to get updates (incl. some uuid), what urls to connect to to push edits?

And we discussed styles need revisiting, since a Mapnik style xml file is far from standalone, and includes things like database credentials, references to external files (fonts, shapefiles, images, etc.)

**Comment by mojodna** [comment]
Sync metadata, e.g. changeset id.

**Comment by mojodna** [comment]
@hallahan is currently building against these.

**Comment by mojodna** [comment]
Automate the contents of `STEPS.md` and `OMK.txt`.

**Comment by hallahan** [comment]
API is coming together. Got a good workflow with shell scripts. Any review and comments appreciated.

https://github.com/AmericanRedCross/posm-admin/tree/f74dec7859ef56568733f74e827252b225a41058

We've got the fetching, untarring, putting things in deployments directory, and driving pyxform to put XLS and XForms in OMK forms dir...

Beginning UI to drive things.

Looking at the code, you'll see that you get a response right a way when an end-point is hit. Since these jobs can be long-lived, updates of what happens in the shell are broadcast through socket.io

At first when downloading form HOT Export tool, the job has a uuid. However, once we crack open the tar.gz and read the manifest, we have the `name` of the deployment, and use that as a handle to updates on the various tasks.

**Comment by hallahan** [comment]
Current 3 things to do:

1. Run through main [admin script]() to do complete provisioning. Tie up loose ends if needed. Make it turn key.
2. Document main script and sub scripts.
3. Outline all of the UI actions (aka buttons) needed.

Regarding building the actual UI, further feedback will be needed from ARC.

**Comment by hallahan** [comment]
`posm-deploy-full.sh` is now operational in a "turnkey" fashion. You just run it, and it works.

I'll document the various scripts and outline what UI actions we need tomorrow.

**Comment by hallahan** [comment]
[sample-hot-export.tar.gz](https://github.com/AmericanRedCross/posm/files/200246/sample-hot-export.tar.gz)

**Comment by hallahan** [comment]
![export-bundle-screenshot](https://cloud.githubusercontent.com/assets/556367/14218394/b6bfe84a-f808-11e5-8d85-f71a4d9b1cde.png)

**Comment by hallahan** [comment]
I have documentation that explains the usage of all of the admin scripts here:

https://github.com/AmericanRedCross/posm-admin/blob/master/docs/scripts.md

Shall we remove STEPS.md and OMK.md now that we have a more streamlined workflow @mojodna ?

**Comment by mojodna** [comment]
I don't think we're quite ready to remove them, though we should simplify STEPS.md in the meantime to take into account what posm-admin landed.

**Comment by mojodna** [comment]
http://tracesof.net/uebersicht/ is a set of desktop widgets defined in CoffeeScript that expose system stats visually. It would be a useful model to build from.

**Comment by mojodna** [comment]
Goal (for system widgets): Dale to be able to repeat the process of creating widgets.

**Comment by mojodna** [comment]
![image](https://cloud.githubusercontent.com/assets/45/14685293/df446e1e-06e8-11e6-8561-4614ec352bb4.png)

**Comment by mojodna** [comment]
To list DHCP leases:

http://linux-tips.org/t/dnsmasq-show-ip-lease-information/231

**Comment by hallahan** [comment]
I think we can consider this done!
