### ISSUE TITLE
Investigate custom NUC cases

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#40]
Desires:
- dust-resistant
- water-resistant
- not crazy expensive

/cc @dalekunce

**Comment by mojodna** [comment]
We also need recommendations on whether external antennas are necessary, recommended, or purely optional.

**Comment by dalekunce** [comment]
might be useful to stress test the AP with 10+ and 20+ connections to see how it handles it.

**Comment by JeremyGrosser** [comment]
How many boxes do we plan to build?

I'll do some testing with an external antenna and report back, but my intuition is that it's going to be recommended in the stock NUC case, and required if we put it in an aluminum case.

LogicSupply seems to be the only reasonably priced off-the-shelf ruggedized NUC case. They'll do custom builds with a builtin battery, so I'll call them on Monday and see what makes sense.
http://www.logicsupply.com/products/components/cases/nuc/

Would anybody be up for doing some testing in the SpatialDev office next week? I'd like to get everybody in the office to connect their phones and laptops to the NUC and see how many devices it can take before things start to break.

**Comment by JeremyGrosser** [comment]
Just talked to LogicSupply... They're going to work up some quotes and get back to me this week. I'll keep looking for another vendor in case LogicSupply comes in too expensive or can't do what we need.

**Comment by JeremyGrosser** [comment]
# Notes
- These are the only rugged NUC boxes currently being sold, based on a list from Intel. There were a few others, but they appear to have been discontinued or not updated to support the current NUC generation.
- There's a pretty compelling case for grabbing some electrical junction boxes and rubber grommets from the hardware store and drilling some holes. I estimate we could build those for ~$45 each.
- Buying enclosures from Logic Supply seems to be the way to go, as it would cost half as much as having them assemble the boxes for us.

# Baseline NUC Pricing
$165 NUC 5PPYH (http://amzn.com/B00XPVQHDU?tag=synack-20)
$70 240GB SSD (http://amzn.com/B00TIJMF84?tag=synack-20)
$35 8GB RAM (http://amzn.com/B00CQ35HBQ?tag=synack-20)
Total: $270

# Logic Supply
Est. Price per Unit: $850 (includes NUC and components)

## Details
Logic Supply is recommending their ML100G-30 based on our requirements (http://www.logicsupply.com/ml100g-30/)

You can play with configuration options there and try out different prices. The config that I think makes sense (8GB memory, 256GB SSD, wireless, terminal block power) comes out to $838. At a quantity of 10, they will not do a volume discount.

They also suggested we look at the DS-1000-10 (http://www.logicsupply.com/ds-1000-10/), one of their more ruggedized designs. The biggest difference is that the DS boxes are designed for a larger temperature range (-10°C to 60°C, rather than 0°C to 50°C). When completely spec'd out, these boxes come out at $1564. I believe this configuration is overkill for our needs. Additionally, they are not based on the NUC design, so we'd have to do a fair bit more testing to qualify this hardware as well.

## DIY
They sell a slightly different model (ML300G http://www.logicsupply.com/ml300g/) for $135 as a standalone case, so we'd do the assembly. With our baseline NUC cost, this would only be $405 per box.

# Akasa Newton H
Est. Price per Unit: $115 (enclosure only) + $270 (baseline NUC) = $385 per box
http://www.akasa.com.tw/update.php?tpl=product/product.detail.tpl&no=181&type=Chassis&type_sub=NUC&model=A-NUC03-A1B

These boxes appear to be designed for home appliance use rather than a rugged solution. It's fanless and looks pretty, but I'd question whether it's more durable than the plastic case the NUC comes with.
