### ISSUE TITLE
OMK requires many top level URLs

### ISSUE THREAD

**Issue by jflemer-ndp** [AmericanRedCross/posm#59]
Since POSM must run multiple apps on the same web server, all apps should use path URL prefixes to avoid conflicts.  Currently OMK has limitations in changing the base url which requires it to use many top level paths, rather than (for instance) having all URLs start with `/omk`.  This complicates proxying and increases the risk of url conflicts.  Refactor OMK to allow using a path prefix or a non-root base URL.

**Comment by mojodna** [comment]
fp-tiler needed access to the original URL in order to generate content, so this is how I added path prefixing:

https://github.com/fieldpapers/fp-tiler/commit/7364e3bb3adc665bc555d07e5205ddb3166c6815

fp-tasks had a different approach taken that didn't involve code changes:

https://github.com/AmericanRedCross/posm-build/blob/master/kickstart/etc/nginx-posm.conf#L39-L41

**Comment by hallahan** [comment]
Completed with https://github.com/AmericanRedCross/posm-build/pull/25
