### ISSUE TITLE
Periodically feed APIDB edits back into rendering DB

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#89]
Osmosis `--read-apidb` → `osm2pgsql` (replacing the existing rendering DB).

**Comment by hallahan** [comment]
Leaning toward having an interface that edits a `crontab` under the hood.

**Comment by mojodna** [comment]
Does it need a UI?

**Comment by hallahan** [comment]
I have attempted to create a temporary render db so that when we are rebuilding, the db isnt in an odd state for mapnik.

However, For a reason I haven't uncovered, sometimes that temp db is missing POSTGIS and HSTORE, though I explicitly create it in posm-build:

https://github.com/AmericanRedCross/posm-build/blob/master/kickstart/scripts/carto-deploy.sh#L19-L20

For now, I'm just rebuilding the `gis` db until I figure out what's going on here. Also, if mapnik is using the gis database, I need to restart postgres to drop all the users accexsing it before the rename.

https://github.com/AmericanRedCross/posm-admin/blob/d1d0f7bf4ce68686de328649becccc4a5033cb48/scripts/gis_render-db-pbf2render.sh#L32

cc/ @mojodna

**Comment by hallahan** [comment]
Right now, every half hour seems to be working fine. The renderer is down for maybe 30 seconds during these times.

```
0,30 * * * * /opt/admin/posm-admin/scripts/render-db-update.sh
```

**Comment by hallahan** [comment]
Done via https://github.com/AmericanRedCross/posm-build/commit/b5d9f0f2b8ddaf4329fa5157a00c0048ef9c398f
