### ISSUE TITLE
External Field Test Issue: Big OSM file does not load in iD editor

### ISSUE THREAD

**Issue by emilyhobson** [AmericanRedCross/posm#99]
- [ ] [Big OSM file does not load in iD editor] https://github.com/AmericanRedCross/OpenMapKitServer/issues/28

**Comment by hallahan** [comment]
Rather than spending a ton of time making the OMK `.osm` endpoint fast and queried by bbox, we have decided to build in the UI the ability to filter by field paper page. That way there isn't a cognitive overload overwhelming the user with a ton of features, and we won't have to handle a fire hose of data. Plus, the user can have a field paper in front of her while validating survey responses. This should be core to the validation workflow. Page-by-field-paper-page to validate. 

You like this idea @dalekunce ?

**Comment by hallahan** [comment]
See https://github.com/AmericanRedCross/posm/issues/121 on first steps to making this happen.

**Comment by mojodna** [comment]
Closed in favor of #125
